### ISSUE TITLE
make: *** [Makefile:17: ignotum/lib/libignotum.a] Error 2

### ISSUE THREAD

**Issue by sorryimastronger** [hc0d3r/mysql-magic#1]
make: *** [Makefile:17: ignotum/lib/libignotum.a] Error 2

**Comment by hc0d3r** [comment]
provide more information, e.g, the full log, command line used, compiler version and your operational system

**Comment by sorryimastronger** [comment]
~/Desktop/mysql-magic-master]
└──╼ $make --version

make -C ignotum lib/libignotum.a
make[1]: se entra en el directorio '/home/luis/Desktop/mysql-magic-master/ignotum'
make[1]: *** No hay ninguna regla para construir el objetivo 'lib/libignotum.a'.  Alto.
make[1]: se sale del directorio '/home/luis/Desktop/mysql-magic-master/ignotum'
make: *** [Makefile:17: ignotum/lib/libignotum.a] Error 2

OS: Parrot Security 4.6
Compiler: GNU make 4.2.1

**Comment by hc0d3r** [comment]
I think the problem is because the ignotum submodule are not being cloned, try run `git clone --recurse-submodules https://github.com/hc0d3r/mysql-magic`, I'll add these instruction to the readme, thank you for reporting.
