### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by gkroon** [hc0d3r/mysql-magic#4]
Hi, I'm improving some of the [Pentoo overlay](https://github.com/pentoo/pentoo-overlay) ebuilds and came across your tool we packaged. Could you add a license for your tool, so that we, but also other developers, can work with your tool? :-)

See https://choosealicense.com/ if you need help picking an open source license (e.g. MIT, GPL).

**Comment by hc0d3r** [comment]
Done, c53da68.
